#����mybatis����ļ�λ��
mybatis:
    mapper-locations: classpath*:mybatis-mapper/*Mapper.xml
    config-location: classpath:mybatis-config.xml
    #ɨ��domain�İ���
    aliasesPackage: com.zy.redisdemo.mapper.model


#����redis
redis:
    host: localhost
    port: 6379
    max-wait: 30000 #���ӳ���������ȴ�ʱ�䣨ʹ�ø�ֵ��ʾû�����ƣ�
    max-active: 100    #���ӳ��������������ʹ�ø�ֵ��ʾû�����ƣ�
    max-idle: 20     #���ӳ��е�����������
    min-idle: 0      #���ӳ��е���С��������
    timeout: 3000    #���ӳ�ʱ


#Spring Boot��Ĭ������ERROR��WARN��INFO�������־���������̨
#ҵ��log����
logging:
    config: classpath:logback-spring.xml
    path: /home/zhangyu/zhangyu-log/
    level:
        com.zy.redisdemo: DEBUG
        com.ibatis: DEBUG